[build]
  publish = "."
  functions = "netlify/functions"

[[plugins]]
  package = "@netlify/plugin-functions-install-core"

[functions."osu-pp"]
  included_files = ["netlify/functions/node_modules/rosu-pp-js/*.wasm"]

[functions."farm-crawl-cron"]
  schedule = "*/10 * * * *"
  included_files = ["netlify/functions/node_modules/rosu-pp-js/*.wasm"]

[functions."farm-crawl-run"]
  included_files = ["netlify/functions/node_modules/rosu-pp-js/*.wasm"]
