/* 自動產生，請勿手動編輯 —— 改用 `node scripts/gen-worker-routes.mjs`。
 * 端點數: 66
 * 排除: 排程 5 個（階段 4 改走 scheduled handler）、
 *       Discord 3 個（延後）、死程式碼 1 個
 */
const { adapt } = require('./adapter');

const ROUTES = {
    "catalog-crawl-run": adapt(require('../netlify/functions/catalog-crawl-run').handler),
    "catalog-list": adapt(require('../netlify/functions/catalog-list').handler),
    "chat-delete": adapt(require('../netlify/functions/chat-delete').handler),
    "chat-edit": adapt(require('../netlify/functions/chat-edit').handler),
    "chat-list": adapt(require('../netlify/functions/chat-list').handler),
    "chat-media": adapt(require('../netlify/functions/chat-media').handler),
    "chat-send": adapt(require('../netlify/functions/chat-send').handler),
    "chat-translate": adapt(require('../netlify/functions/chat-translate').handler),
    "chat-upload": adapt(require('../netlify/functions/chat-upload').handler),
    "collection-share-page": adapt(require('../netlify/functions/collection-share-page').handler),
    "collections-get": adapt(require('../netlify/functions/collections-get').handler),
    "collections-like": adapt(require('../netlify/functions/collections-like').handler),
    "collections-list": adapt(require('../netlify/functions/collections-list').handler),
    "collections-publish": adapt(require('../netlify/functions/collections-publish').handler),
    "collections-unpublish": adapt(require('../netlify/functions/collections-unpublish').handler),
    "community-mappools-crawl-run": adapt(require('../netlify/functions/community-mappools-crawl-run').handler),
    "community-mappools-edit": adapt(require('../netlify/functions/community-mappools-edit').handler),
    "community-mappools-list": adapt(require('../netlify/functions/community-mappools-list').handler),
    "dm-conversations": adapt(require('../netlify/functions/dm-conversations').handler),
    "dm-messages": adapt(require('../netlify/functions/dm-messages').handler),
    "dm-read": adapt(require('../netlify/functions/dm-read').handler),
    "dm-send": adapt(require('../netlify/functions/dm-send').handler),
    "embed-collection": adapt(require('../netlify/functions/embed-collection').handler),
    "farm-crawl-run": adapt(require('../netlify/functions/farm-crawl-run').handler),
    "farm-maps-list": adapt(require('../netlify/functions/farm-maps-list').handler),
    "gallery-comments-delete": adapt(require('../netlify/functions/gallery-comments-delete').handler),
    "gallery-comments-list": adapt(require('../netlify/functions/gallery-comments-list').handler),
    "gallery-comments-post": adapt(require('../netlify/functions/gallery-comments-post').handler),
    "gallery-feed": adapt(require('../netlify/functions/gallery-feed').handler),
    "games-daily": adapt(require('../netlify/functions/games-daily').handler),
    "games-hilo": adapt(require('../netlify/functions/games-hilo').handler),
    "games-leaderboard": adapt(require('../netlify/functions/games-leaderboard').handler),
    "games-quiz": adapt(require('../netlify/functions/games-quiz').handler),
    "og-collection": adapt(require('../netlify/functions/og-collection').handler),
    "osekai-medals": adapt(require('../netlify/functions/osekai-medals').handler),
    "osu": adapt(require('../netlify/functions/osu').handler),
    "osu-avatar": adapt(require('../netlify/functions/osu-avatar').handler),
    "osu-beatmapset": adapt(require('../netlify/functions/osu-beatmapset').handler),
    "osu-callback": adapt(require('../netlify/functions/osu-callback').handler),
    "osu-login": adapt(require('../netlify/functions/osu-login').handler),
    "osu-mapper-status": adapt(require('../netlify/functions/osu-mapper-status').handler),
    "osu-news": adapt(require('../netlify/functions/osu-news').handler),
    "osu-pp": adapt(require('../netlify/functions/osu-pp').handler),
    "osu-pp-history": adapt(require('../netlify/functions/osu-pp-history').handler),
    "osu-score-history": adapt(require('../netlify/functions/osu-score-history').handler),
    "osu-tournaments": adapt(require('../netlify/functions/osu-tournaments').handler),
    "osu-user-achievements": adapt(require('../netlify/functions/osu-user-achievements').handler),
    "osu-user-beatmapsets": adapt(require('../netlify/functions/osu-user-beatmapsets').handler),
    "push-config": adapt(require('../netlify/functions/push-config').handler),
    "push-subscribe": adapt(require('../netlify/functions/push-subscribe').handler),
    "replay-analyze": adapt(require('../netlify/functions/replay-analyze').handler),
    "site-likes": adapt(require('../netlify/functions/site-likes').handler),
    "skin-screenshots-delete": adapt(require('../netlify/functions/skin-screenshots-delete').handler),
    "skin-screenshots-download": adapt(require('../netlify/functions/skin-screenshots-download').handler),
    "skin-screenshots-image": adapt(require('../netlify/functions/skin-screenshots-image').handler),
    "skin-screenshots-like": adapt(require('../netlify/functions/skin-screenshots-like').handler),
    "skin-screenshots-list": adapt(require('../netlify/functions/skin-screenshots-list').handler),
    "skin-screenshots-upload": adapt(require('../netlify/functions/skin-screenshots-upload').handler),
    "skins-delete": adapt(require('../netlify/functions/skins-delete').handler),
    "skins-download": adapt(require('../netlify/functions/skins-download').handler),
    "skins-list": adapt(require('../netlify/functions/skins-list').handler),
    "skins-upload": adapt(require('../netlify/functions/skins-upload').handler),
    "trending-songs": adapt(require('../netlify/functions/trending-songs').handler),
    "wc-mappool-crawl-run": adapt(require('../netlify/functions/wc-mappool-crawl-run').handler),
    "wc-mappools-list": adapt(require('../netlify/functions/wc-mappools-list').handler),
    "wybin-tournaments": adapt(require('../netlify/functions/wybin-tournaments').handler),
};

/* 排程函式不掛 HTTP 路由，但階段 4 的 scheduled handler 需要拿得到。 */
const CRON_HANDLERS = {
    "catalog-crawl-cron": require('../netlify/functions/catalog-crawl-cron').handler,
    "community-mappools-crawl-cron": require('../netlify/functions/community-mappools-crawl-cron').handler,
    "farm-crawl-cron": require('../netlify/functions/farm-crawl-cron').handler,
    "push-cron": require('../netlify/functions/push-cron').handler,
    "wc-mappool-crawl-cron": require('../netlify/functions/wc-mappool-crawl-cron').handler,
};

module.exports = { ROUTES, CRON_HANDLERS };
